---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: /ProfessionalResponsibility # the subpath of your site, e.g. /blog/
title: Professional Responsibility 
description:  # leave blank if you don't want to display a description 
last_updated: 26 August 2020 # leave blank if you don't want to display last updated

name: Professional Responsibilty 
author: Eric M. Fink
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334

collections: 
  cases: 
    output: true 
  exams:
    output: true
  notes: 
    output: true 
  outlines:
    output: true
  problems:
    output: true 
  questions:
    output: true
  readings: 
    output: true 
  statutes: 
    output: true 
  visuals:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
remote_theme: luckyjimjd/lj-folio

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
