url: https://www.emfink.net
baseurl: /ProfessionalResponsibility
title: Professional Responsibility

last_updated: 28 August 2023  # leave blank if you don't want to display last updated

author:
  name:  Eric M. Fink
  positition: Associate Professor
  affiliation: Elon Law School 
  address: "201 North Greene Street, Greensboro, North Carolina 27408"
  email: efink@elon.edu
  phone: 336-279-9334
  web: emfink.net/ElonLaw

ta: 
  name: Elizabeth Kwon
  email: ekwon@elon.edu

course: 
  subject: Professional Responsibility
  term: Fall 2023
  room: Room 207 
  meets: "Monday & Wednesday 9:45–10:45 am"
  repository: ProfessionalResponsibility

coursebook:
  title: Professional Responsibility
  subtitle: An Open-Source Casebook
  version: '2.1'
  date: August 2023

collections:
  casebook:
    output: true


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings

# deployment
host: localhost
port: 4000

remote_theme: EricMFink/akademicky

gems:
  - jekyll-pandoc

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:categories/:year/:month/:day/:title/
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
include: ['_pages']
exclude: ['Gemfile.lock', admin, .admin]
keep_files: [.admin]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: code
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/EricMFink.github.com/

jquery_version: "1.12.4"
anchorjs_version: "3.2.2"

plugins:
  - jekyll-spaceship

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
